cookie:
  expiry_days: 0
  key: streamlit-auth-test-app-key
  name: streamlit-auth-test-app
credentials:
  usernames:
    brian:
      email: brian@example.com
      failed_login_attempts: 0
      first_name: Brian
      last_name: Roepke
      logged_in: false
      password: $2b$12$jLY6Vm1eAt1CO9aWaZvX1uucXRh0WxJxfS/y6gGZGKpJsQNfC/ahm
      roles:
      - admin
      - editor
      - viewer
